test: add cluster tests
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,15 +42,18 @@ jobs:
     - name: Exercice lxd-https relation
       run: |
         set -eux
+        STEP_NAME="lxd-https relation"
+        echo "# === $STEP_NAME starts === #" >> juju-debug.log
 
         # capture juju's logs on error
         debug() {
             rc="$?"
             set +e
-            juju debug-log --replay --level DEBUG > juju-debug.log
+            juju debug-log --replay --level debug >> juju-debug.log
+            echo "# === $STEP_NAME ends === #" >> juju-debug.log
             exit "$rc"
         }
-        trap debug ERR EXIT
+        trap debug err exit
 
         juju deploy ./lxd_ubuntu-20.04-amd64.charm --num-units 1 --config sysctl-tuning=false --config kernel-hardening=false --config lxd-listen-https=true
         juju deploy ./https-client_ubuntu-20.04-amd64.charm --config autoremove=false
@@ -73,18 +76,43 @@ jobs:
         ! juju run --unit lxd/leader -- lxc config trust list --format csv | grep -E ",juju-relation-.+-https-client/[0-9]+:autoremove,"
         juju status --relations
 
-    - uses: actions/upload-artifact@v2
-      with:
-        name: juju-debug-logs ${{ github.job }}
-        path: juju-debug.log
-        retention-days: 5
-
     - name: Scale the number of lxd units
       run: |
         set -eux
         juju add-unit lxd --num-units 3
         juju wait
         juju status
+
+    - name: Cleanup standalong lxd units
+      run: |
+        set -eux
+        juju remove-application --force lxd
+        juju wait
+        juju status
+
+    - name: Cluster tests
+      run: |
+        set -eux
+        STEP_NAME="cluster tests"
+        echo "# === $STEP_NAME starts === #" >> juju-debug.log
+
+        # capture juju's logs on error
+        debug() {
+            rc="$?"
+            set +e
+            juju debug-log --replay --level debug >> juju-debug.log
+            echo "# === $STEP_NAME ends === #" >> juju-debug.log
+            exit "$rc"
+        }
+        trap debug err exit
+
+        NODE_CREATED="3"
+        juju deploy ./lxd_ubuntu-20.04-amd64.charm --num-units "$NODE_CREATED" --config sysctl-tuning=false --config kernel-hardening=false --config mode=cluster
+        juju wait
+        juju status --relations
+
+        NODE_JOINED="$(juju run --unit lxd/leader -- lxc cluster list --format csv | grep -cF ',ONLINE,Fully operational')"
+        [ "$NODE_JOINED" -eq "$NODE_CREATED" ]
 
     - name: Check for errors
       run: |
@@ -94,3 +122,11 @@ jobs:
             juju status --format=oneline
             exit 1
         fi
+
+    - name: Juju debug-log
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: juju-debug-logs ${{ github.job }}
+        path: juju-debug.log
+        retention-days: 5
